### ISSUE TITLE
Questions about pin map table

### ISSUE THREAD

**Issue by rwaldron** [intel-iot-devkit/mraa#104]
In the table https://github.com/intel-iot-devkit/mraa/blob/master/docs/edison.md#intelr-breakout-board, what do the following mean: 

1. "NC"
2. "Nothing from mraa"

**Comment by tingleby** [comment]
https://communities.intel.com/docs/DOC-23252
NC = No Connect

Nothing from mraa was just a perhaps badly worded status saying mraa has nothing todo with that pin other than it being aware its there for padding.

**Comment by rwaldron** [comment]
Thanks!
