### ISSUE TITLE
curious: what does mraa stand for?

### ISSUE THREAD

**Issue by ddnionio** [intel-iot-devkit/mraa#109]
just a question: what does mraa mean? why it is called "mraa"?

and what does upm stand for?

**Comment by arfoll** [comment]
It's short, easy to type and means whatever you want/nothing, though i think the first letter stands for 'monkeys'.

**Comment by ddnionio** [comment]
sorry, i still cant understand. why "mraa" means "whatever you want/nothing", and what the relationship with monkeys...
I searched a long time in the web, and no one tells why it is called “mraa” or “upm”

**Comment by arfoll** [comment]
Upm is meant to be useful packages for mraa. Mraa means nothing, sorry to disappoint I'm just bad/have complete disregard for picking project names.
