### ISSUE TITLE
SPI Interface not fully initialized on mraa_spi_init

### ISSUE THREAD

**Issue by michael-ring** [intel-iot-devkit/mraa#112]
I found out that on the Beaglebone I need to first set the spi Interface Mode before the interface works correctly.

There are now two possible ways to solve this, either

initialize spi as master per default on mraa_spi_init 

or

change the examples so that they always include a call to mraa_spi_mode

I can provide patches for both, I have no access to galileo/minnow/nuc board so I cannot test if it hurts to do set a default spi mode on init.

I can provide patches for both versions.

**Comment by tingleby** [comment]
Thanks Michael!
Out of the two I think "initialize spi as master per default on mraa_spi_init" would be a better fit.
Please go ahead and provide a patch, I will test it out on at least the galileo/edison.

**Comment by michael-ring** [comment]
Will do.

Could you please reject my previous pull request, I would like to create a new pull request and take into account the tips I received for the old one. I found out that with the github UI it is only possible to handle one pull request to one repo, there seem to be workarrounds for this but I think it is easier to trash the hole request and to start over with more atomic patches.

**Comment by tingleby** [comment]
Are you talking about #95 ?
If you were to submit the PR from a branch then you can have as many PRs as you feel like. If you take a look at AlexT's #111 it has been submitted from a "feature" branch.
Just found this link to try and provide you a rough guide, http://blog.milkfarmsoft.com/2011/03/on-feature-branches/

**Comment by michael-ring** [comment]
Thank you, I will have a look at this

**Comment by michael-ring** [comment]
Fixed in pull request #125

**Comment by arfoll** [comment]
Closed as this is no longer an issue as I understand?
