### ISSUE TITLE
PWM write() accepts values bigger than "1" as parameter

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#121]
Hello,

While doing a test on mraa v0.5.4-118-g818e1a8  I noticed in Python that for PWM class, the write() method accepts values for duty cycle bigger than 1, which physically is not correct. It returns no error though and considered the value to be a duty cycle of 1 (like a logic 1)

It would be nice to have a small message that when such a value is introduced something like "Warning: duty cycle value should be between 0 and 1; considering 1 instead of %f" to be displayed.
# tested on Galileo v1
>>> import mraa as m
>>> pwm=Pwm(3)
>>> pwm.period_us(1000) # 1kHz frequency
>>> pwm.enable(True)
>>> pwm.write(5)
0

Regards,

Costin

**Comment by tingleby** [comment]
This was done on purpose, a warn message to syslog could be added.
