### ISSUE TITLE
Need a way of getting pin name from platform config

### ISSUE THREAD

**Issue by michael-ring** [intel-iot-devkit/mraa#127]
Is there a reason why the pin description was removed from gpio list?

Output now looks a little empty for buttons without function (like GND and VCC):

01
02
03 GPIO I2C
04
05 GPIO I2C

**Comment by arfoll** [comment]
Yes, we changed gpio to use the public api instead of hackily recovering the platform config. There's currently no public API to get the pin 'name'.

A function of the style `char* mraa_pin_name(int pin);` could be implemented if there's interest.

**Comment by michael-ring** [comment]
Yes, there's interest ;-) 

Assign it to me, then I will add this and change gpio to use it.

**Comment by arfoll** [comment]
Closd by 827e1974bf12d9b318883818b9078f9b44335ad8
