### ISSUE TITLE
readReg()  from I2C accepts false addresses 

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#129]
Hello,

Not sure if this is a bug or not, but when trying readReg() with a false value for the register address, it returns 0L. This can be confusing, because one cannot know when this is correct or not. However, writeReg() does it's job fine by returning exit code 5 when a wrong address is used.

>>> m.getVersion()
'v0.5.4-118-g818e1a8'

Regards,

Costin

**Comment by arfoll** [comment]
Not much we can do about that because an operation is only performed on a
read/write.

**Comment by cosscat** [comment]
Thank you arfoll. I imagined what you said, and this is why i said not sure if it's a bug. 

Regards,

Costin
