### ISSUE TITLE
How to generate node module for mraa?

### ISSUE THREAD

**Issue by abdullahyildiz** [intel-iot-devkit/mraa#130]
How can I generate mraa.node under /usr/lib/node_modules/mraa directory so that I can use my own compiled version of it?

**Comment by arfoll** [comment]
If you want a full source build you need to follow the building instructions - https://github.com/intel-iot-devkit/mraa/blob/master/docs/building.md (you'll need SWIG 3.x).

**Comment by abdullahyildiz** [comment]
OK. It worked.
