### ISSUE TITLE
UART module accepts initialising with the port no of the serial console

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#138]
Hello,

I did this test on Galileo v1 and when initialising Uart with port no. 1 it reports no warning/error message. The /dev/ttyS1 is assigned to the serial console (the on-board jack alike serial port). Also getDevicePath() reports back the assigned port:

>>> import mraa as m, serial as s
>>> uart=m.Uart(1)
>>> uart.getDevicePath()
'/dev/ttyS1'

Costin

**Comment by arfoll** [comment]
@cosscat I'm not too sure if we want to fix this, it's nice to be able to use that serial port from mraa if the user wants and at the same time there's no good platform independant way of finding out if a serial port is already in use. We could hack something up to check systemd services/gettys but I think that's horribly nasty.

The best I can think of is to document this in the galileo gen1 platform doc file. What do you think?

**Comment by cosscat** [comment]
Hi Brendan, 

Sorry for the delay in getting back to this. Yes, i guess what you said is fine. Adding something to the doc file is best.

**Comment by alext-mkrs** [comment]
I've just checked the sources and what's interesting is that for Gen1 we specify two UART devices in the platform config file, while for Gen2 we specify only one (excluding the one with the console). Is there any specific idea behind this? Should we maybe align the two and then document as already agreed in this thread?

**Comment by tingleby** [comment]
I went ahead and aligned them, no reason not to.
