### ISSUE TITLE
[platform] Improve behaviour when running on platforms not yet defined

### ISSUE THREAD

**Issue by tripzero** [intel-iot-devkit/mraa#142]
Running mraa on my haswell-based desktop, I got "Intel Galileo Gen 1" when querying getPlatformName().

**Comment by tingleby** [comment]
Yes, this is the current expected behaviour if mraa is running on a platform is is not equipped to work with. If you check your syslog, it should be complained a plenty in there.

**Comment by tripzero** [comment]
Shouldn't it return ""?  Or "unknown system"?

**Comment by tripzero** [comment]
Let me describe the use-case that's broken here:

Let's say you want to write a higher-level library that introspects mraa using getPlatformName and uses pre-defined pin settings for that platform.

If an unknown system returns "Intel Galileo Gen 1", then the pin-outs will be wrong and the library will be broken

**Comment by tingleby** [comment]
This is an element of legacy behaviour, nerveless something that could do with a rethink.

My current proposal is: When the library is run on a system without additional definitions it will attempt to find the limitations of the current system, and in the case of getPlatformName return something like unknown.

**Comment by arfoll** [comment]
Agreed this behaviour was pretty rubbish, it makes no sense now that we support quite a few platforms, fixed & changed. Note that arm module by default will init an rpi as well. This is a bit more difficult to treat since arm platforms rarely have a nicely exported name such as the one in DMI.

**Comment by tingleby** [comment]
Now the behaviour is
```
mraa: FATAL error, failed to initialise platform
hello mraa
 Version: v0.6.1-8-g2c74ba7
 Running on (null)
```
@arfoll I'll talk to you later about my further plans for this.
