### ISSUE TITLE
Changing i2c bus speed on Edison

### ISSUE THREAD

**Issue by lectroidmarc** [intel-iot-devkit/mraa#145]
I apologize if I'm totally off base here, my C is a bit weak so I'm just going to ask stupid questions...

In [mraa_intel_edison_i2c_freq()](https://github.com/intel-iot-devkit/mraa/blob/e8bc227a92fa702bceef5052961123c2e511e811/src/x86/intel_edison_fab_c.c#L675) it appears that to change the I2c bus speed it's trying to write "std/fast/high" to `/sys/devices/pci0000:00/0000:00:09.1/i2c_dw_sysnode`.  The problem is, on my Edison, `/sys/devices/pci0000:00/0000:00:09.1/i2c_dw_sysnode` is a *directory* containing two files `bus_num` and `mode`.

So, shouldn't it be trying to change `/sys/devices/pci0000:00/0000:00:09.1/i2c_dw_sysnode/mode`?

Further, could `mraa_intel_edison_i2c_freq()` be updated to also change the file `/sys/devices/pci0000:00/0000:00:08.0/i2c_dw_sysnode/mode` to change I2C1 as well?

Thanks.

**Comment by arfoll** [comment]
Hi @lectroidmarc, you're 100% right, I have no idea how this worked previously - what's weird is that I checked with a scope and all... maybe the folder structure changed between the test build I used and the r2 edison SW release.... In any case I've fixed it with 677af126aab3c3773f5bd26ca17ba917c9403216.

I've also had a look at i2c bus 1, I think I've got the correct path but I can't check as I dont have physical access to an edison until monday and mine is on an arduino breakout. i2c-6 seems to switch well at least. Can you confirm it's working now? FYI - you can grab the latest prebuilds from http://iotdk.intel.com/repos/1.1/intelgalactic-dev/ just go to /etc/opkg/mraa-upm.conf on your board and switch add '-dev' to the intelgalactic folder. (it should be built within the next few minutes).
