### ISSUE TITLE
Feature Request: 1-wire support

### ISSUE THREAD

**Issue by jmealo** [intel-iot-devkit/mraa#154]
Please add 1-wire support to mraa.

It looks like it should be supported in Yocto.

Does anyone have any progress on this?

**Related links:**
[1] http://bigdinotech.com/tutorials/galileo-tutorials/using-1-wire-device-with-intel-galileo/
[2] https://groups.google.com/forum/#!topic/wandboard/fPf1fbEj9Io
[3] https://communities.intel.com/thread/56822
[4] http://owfs.org/

**Comment by arfoll** [comment]
You'll have to be more specific, the problem with one wire is one it's reliance on exact timings which from userspace linux is 'hard'. The other issue is that it's heavily board dependant and alot of sensors handle it differently. Hacking it as your [1] shows is trivial from mraa.

It would be interesting to have a look at how to use it from the kernel and expose that from mraa, the 1wire driver seems to however use device tree which galileo/edison does not so this would require a bit of thinking to make it work on intel boards.

**Comment by akulo** [comment]
how about DS18B20 support?

**Comment by wawrow** [comment]
I've tried using ds18b20 with edison but it seems like it wasn't switching in/out on gpio fast enough for 1wire, could probably be done with two gpios, but i haven't got a chance to try it out.

**Comment by akulo** [comment]
the idea is to have it somehow exposed to node.js to consume without knowing all the implementation details

**Comment by mulderp** [comment]
A nice example of 1-wire protocol might be the DHT-22: http://www.adafruit.com/datasheets/DHT22.pdf - the DHT series is quite popular in Arduino examples (it's very cheap), e.g. see https://www.adafruit.com/products/386

**Comment by mulderp** [comment]
sorry, dht-xx is not one wire: http://forum.arduino.cc/index.php?topic=253899.0

**Comment by alext-mkrs** [comment]
Support for 1-wire via UART was merged with a379eb7bf66a7a31a3b95b9bf239dffaaec241a6 and I think it's as close as we can get to it, given the OS we have on board.

@arfoll, do you think we can close this one as done? I would think so.

**Comment by arfoll** [comment]
Indeed, completely forgot this bug :) Closed!
