### ISSUE TITLE
Some definitions in common.h belong elsewhere

### ISSUE THREAD

**Issue by eschaton** [intel-iot-devkit/mraa#155]
There are a couple of definitions in `<mraa/common.h>` that really belong in different files:

- `mraa_boolean_t` should be in `<mraa/types.h>`
- `mraa_adc_raw_bits()` and `mraa_adc_supported_bits()` should be in `<mraa/aio.h>`

**Comment by arfoll** [comment]
Note they are _adc_ functions not _aio_ functions. Realistically they allow you to query the platform config not the Aio module. I see no real harm in keeping them where they are - any particular reason why you want to move them?

**Comment by eschaton** [comment]
I just figured all analog I/O stuff — which is how I think of ADC anyway — would be in the same place in the API.
