### ISSUE TITLE
Node: I2C readBytesReg commands are backwards

### ISSUE THREAD

**Issue by srlmproductions** [intel-iot-devkit/mraa#168]
I have the following program:

```javascript
'use strict';

var mraa = require('mraa');
console.log('mraa version: ' + mraa.getVersion());

var device = new mraa.I2c(1);
device.address(0x1D);

// Correct ordering
device.readWordReg(0x28 | 0x80);

// Incorrect ordering
device.readBytesReg(0x28 | 0x80, 6);
```

The `readWordReg()` function produces the following trace:
![readwordregorder](https://cloud.githubusercontent.com/assets/5284696/6631390/bcee94e2-c8fb-11e4-9aa7-6df407c3e0e5.png)
Notice the write, then the read.

The `readBytesReg()` function produces the following trace:
![readbytesregorder](https://cloud.githubusercontent.com/assets/5284696/6631397/cf0c95c0-c8fb-11e4-9617-2f7297e383f5.png)
Notice the read, then the write.

The `readBytesReg()` function appears to put the read and write into the wrong order on the I2C bus.

I tested this with an [LSM9DS0](https://www.sparkfun.com/products/13033).

Environment: Edison using mraa v0.6.1-14-g0dd0395 under Node v0.10.36 on Ubilinux Debian 7 (wheezy).

**Comment by arfoll** [comment]
Fixed
