### ISSUE TITLE
python SPI: lsbmode() accepts False but not True

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#178]
Hello,

On Galileo v1, the lsbmode(True) returns errcode 7:

>>> spi=m.Spi(0)
>>> spi.lsbmode(False)
0
>>> spi.lsbmode(True)
7
>>>
>>> m.getVersion()
'v0.6.1'

Costin

**Comment by arfoll** [comment]
galileo g1 does not seem to support lsbmode LSB_FIRST. Thus the ioctl's fail at a kernel level returning MRAA_ERROR_INVALID_RESOURCE (ideally on fail it should return MRAA_ERROR_FEATURE_NOT_SUPPORTED) we should add a _replace() hook for this on g1.
