### ISSUE TITLE
The getPinName() routine is absent

### ISSUE THREAD

**Issue by dyosick** [intel-iot-devkit/mraa#183]
According to the documentation to the 0.6.1 release (http://iotdk.intel.com/docs/master/mraa/namespacemraa.html#aa436b58bf20a87909c7344bf58d42706), but the compiler says:
"aio.c: In function ‘int main()’:
aio.c:6:38: error: ‘getPinName’ is not a member of ‘mraa’"

**Comment by tingleby** [comment]
What version of mraa do you have installed?
`opkg info libmraa0`

**Comment by arfoll** [comment]
More importantly this is not a feature of v0.6.1 but is a feature for
upcoming releases:
http://iotdk.intel.com/docs/mraa/v0.6.1/namespacemraa.html#aa436b58bf20a87909c7344bf58d42706

You need to use master from intelgalactic-dev to get that function.

On 7 April 2015 at 11:04, Tom Ingleby <notifications@github.com> wrote:

> What version of mraa do you have installed?
> opkg info libmraa0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/intel-iot-devkit/mraa/issues/183#issuecomment-90494284>
> .
>



-- 
Brendan Le Foll
http://www.madeo.co.uk

**Comment by dyosick** [comment]
Sorry, guys, it's my fault. I've looked into the wrong doc page. Thanks for help.
