### ISSUE TITLE
[Galileo gen2] Analog pin defect?

### ISSUE THREAD

**Issue by rwaldron** [intel-iot-devkit/mraa#20]
With nothing attached to the analog pins: 

Test:
```js
var m = require("mraa");
for (var i = 0; i < 6; i++) {
  console.log(new m.Aio(i).read());
}
```
Result: 
```
1016
224
1021
1022
993
882
```

Test: 
```python
import mraa

for x in range(0, 6):
  print mraa.Aio(x).read()
```

Result: 
```
1020
218
1021
1022
993
883
```

Disregarding the line noise, A1 is obviously experiencing some issue and I'm not sure how to find it. This may not even be an mraa issue, but I don't know where else to report.

_edit_

If I put a jumper across 5V and A1, the value is a nice 1023.

**Comment by alext-mkrs** [comment]
@arfoll, have you ever heard back from HW team on this?

**Comment by arfoll** [comment]
Closing as this is a hardware issue but I'm not getting a good answer.
