### ISSUE TITLE
Incorrect return value for mraa_i2c_read_bytes_data

### ISSUE THREAD

**Issue by yongli3** [intel-iot-devkit/mraa#218]
According the Doc in http://iotdk.intel.com/docs/master/mraa/i2c_8h.html#aa18cc27c8137f078030e4d862ed5e346:
Returns
The length in bytes passed to the function or 0

However the source code is:     return ioctl(dev->fh, I2C_RDWR, &d) < 0 ? -1 : length;

Return -1 is inconsistence with the document

**Comment by arfoll** [comment]
Thanks alot, great spot.
