### ISSUE TITLE
[Edison] mraa_spi_lsbmode Does not have any affect

### ISSUE THREAD

**Issue by versamodule** [intel-iot-devkit/mraa#22]
using mraa_spi_lsbmode(spi,0) or mraa_spi_lsbmode(spi,1) does not have any affect on how data is sent. 

also, the function for it could be trimmed up a bit by getting rid of the first if statement. to this:

mraa_result_t
mraa_spi_lsbmode(mraa_spi_context dev, mraa_boolean_t lsb)
{
    uint8_t lsb_mode = (uint8_t) lsb
...

**Comment by Yoda12999** [comment]
Is there a possibility that the SPI device on the Edison does not support LSB mode? I have looked at the documentation for the Atom processor and it says nothing about this, but this is a rather odd feature.

**Comment by alext-mkrs** [comment]
While preparing a fix for issue #178 I've came across this issue too. I'm going to look more into this to see if I can find any additional clues, however as a data point - below is what I see in the `dmesg` output when trying to set lsbmode to true (the log has several attempts listed, it's one line per one lsbmode function invocation):
```
[  697.786230] spidev spi5.1: setup: unsupported mode bits 8
[  723.823990] spidev spi5.1: setup: unsupported mode bits 8
[  737.880541] spidev spi5.1: setup: unsupported mode bits 8
[  761.673874] spidev spi5.1: setup: unsupported mode bits 8
[ 2488.659357] spidev spi5.1: setup: unsupported mode bits 8
```

**Comment by alext-mkrs** [comment]
After looking into the driver and Linux SPI sources I would say it is indeed the case that Edison's SPI controller we use in MRAA doesn't support LSB_FIRST mode, just as that log message I pasted above confirms.

@arfoll, shouldn't we implement the same _replace hook function for Edison as for the Galileo Gen1 in #178?

**Comment by arfoll** [comment]
Yes, the same _replace hook would probably be a good idea. Are you willing to send a patch for this as well?

**Comment by alext-mkrs** [comment]
Yep, will do
