### ISSUE TITLE
char() helper function in Javascript example code unnecessary 

### ISSUE THREAD

**Issue by robotskirts** [intel-iot-devkit/mraa#226]
The char() helper function in the js example code isn't necessary.

In bmp85.js for example:

x.address(0x77)

is used to set the address and is perfectly fine. But later

x.writeReg(char('0xf4'), char('0x2e'))

this isn't needed at all, the following piece of code does the same thing

x.writeReg(0xf4, 0x2e)

This superfluous code makes the examples hard to understand.

**Comment by arfoll** [comment]
Yes you're right they're no longer needed, I'll test the samples and update them
