### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by FlippieCoetser** [intel-iot-devkit/mraa#230]
Hi,

With reference to #208, I was able to reproduce another Segment Fault

Node application using ```MRAA v.06.2``` and ```Node v.0.12.3```: 
- HTTP Server for Website running on port ```192.168.2.147:10000```
- Interrupt configured on ```GPIO(36)``` with ``` DIR_IN, EDGE_RISING ```.

Reproducing Segmentation Fault:
1. Start Application ```node app.js```
2. Trigger external Interrupt > Input: Click

![image](https://cloud.githubusercontent.com/assets/3672126/8397367/2c15bd6a-1dc9-11e5-96b5-54c8083debc2.png)

3. Browse to Website ```http://192.168.2.147:10000/```
4. Trigger external Interrupt again

![image](https://cloud.githubusercontent.com/assets/3672126/8397371/478e5822-1dc9-11e5-9869-fa0f5a5f6ac6.png)

Here is the full backtrace
Thread 8
![image](https://cloud.githubusercontent.com/assets/3672126/8397387/ef4021f4-1dc9-11e5-8f07-0af25f20527d.png)
Thread 7
![image](https://cloud.githubusercontent.com/assets/3672126/8397389/fa638936-1dc9-11e5-80f0-276285c3f438.png)
Thread 6
![image](https://cloud.githubusercontent.com/assets/3672126/8397393/0b1b6cda-1dca-11e5-805e-ede9b7779176.png)
Thread 5
![image](https://cloud.githubusercontent.com/assets/3672126/8397394/169b340a-1dca-11e5-920d-ca4a8271155d.png)
Thread 4
![image](https://cloud.githubusercontent.com/assets/3672126/8397396/2a3cd0cc-1dca-11e5-83c7-4047737e4fa6.png)
Thread 3
![image](https://cloud.githubusercontent.com/assets/3672126/8397400/36d16032-1dca-11e5-8004-04969157e25d.png)
Thread 2
![image](https://cloud.githubusercontent.com/assets/3672126/8397402/4a118b4a-1dca-11e5-8bde-f8759cad9009.png)
Thread 1
![image](https://cloud.githubusercontent.com/assets/3672126/8397403/55f909f6-1dca-11e5-9887-6a96e2a9d485.png)

Any suggestion?

Regards,
Flippie

**Comment by arfoll** [comment]
Unfortunately unless I can reproduce there's not much I can do, can you send me some code which reproduces this on node.js 0.12?

**Comment by FlippieCoetser** [comment]
I have stripped down the application to only include three components:
- HTTP Webserver ```WebApp.js```
- Interrupt Configuration ```Core.js```
- Event Management ```Event.js```

The application entry is ```Main.js```
I created a public git repository with the App: https://github.com/FlippieCoetser/mraaTestApp.git

To reproduce:
- ```Node Main.js```
- Trigger the Interrupt ```GPIO(36),  DIR_IN, EDGE_RISING```
- Browse to web app ```<IP Address>:10000```
- Trigger the Interrupt again  ```Segmentation Fault```

Loading files to ```HTTP Webserver``` using either ```FS.readFile or FS.readFileSync``` together with ```MRAA``` cause ```Segmentation Fault.```

Regards,
Flippie

**Comment by FlippieCoetser** [comment]
@arfoll I upgraded 

```mraa``` to ```v0.7.3-2-gdf0dbb0``` and
```node``` to ```v0.12.7```

No change, still get the same segmentation fault as above. 
I have attached a github link in the previous post so that you are able to reproduce the segmentation fault on your side.

Any help will be much appreciated!

Regards,
Flippie

**Comment by arfoll** [comment]
Are you on ubilinux?

**Comment by FlippieCoetser** [comment]
Yes, using the latest Ubilinux. However I did have the same problem before #208 , on a Yockto Image. I suspect the problem is with some conflict between Interrupt and Filesystem features used in Node.js

**Comment by arfoll** [comment]
Yes but you said it was fixed by moving to 0.12.x which is fairly likely as the ISR path used with that v8 version is quite a bit better. This seems like a different bug.

**Comment by FlippieCoetser** [comment]
Agree, could be a different bug. If there is anything that you want to try out just let me know. Happy to do so!

**Comment by alext-mkrs** [comment]
@FlippieCoetser is this still actual? Could you please try with mraa 0.8.1 and whatever Node.js you prefer these days?

**Comment by alext-mkrs** [comment]
Closing as no response and potential fix provided. Feel free to add a comment if you need further help.
