### ISSUE TITLE
Segmentation fault using variable number of arguments

### ISSUE THREAD

**Issue by sukeshak** [intel-iot-devkit/mraa#235]
// Getting segmentation fault
void myprintf(const char * fmt, ...)
{
	char temp[24];
	va_list args;
	va_start(args,fmt);
	sprintf(temp,fmt,args);
	va_end (args);
	printf (temp); // using this for printing to OLED (sparkfun Edison OLED block)
}
int main()
{
	double d = 1234.56;
	myprintf("val: %f",d);
	return 0;
}

**Comment by arfoll** [comment]
I don't understand where the mraa issue is here?

**Comment by arfoll** [comment]
Closing as no update. Likely you need to use vprintf since a va_list != va_arg.

**Comment by sukeshak** [comment]
Thank you Brendan. Sorry could not revert since my hard disk crashed 😞

~Sukesh
________________________________
