### ISSUE TITLE
"mraa: i2c filename file too big, skipping" error message

### ISSUE THREAD

**Issue by yongli3** [intel-iot-devkit/mraa#236]
After upgraded to 0.7.3, I found the error message on DE3815:
mraa: i2c filename file too big(4096), skipping
mraa: no i2c-dev detected, load i2c-dev

The I2C does not work. I found the #define MAX_SIZE 64 should be:
#define MAX_SIZE 4097

**Comment by arfoll** [comment]
Fixed with 66e6d8adcddb7211cdcf54d0c81b88ca74e5aa4b
