### ISSUE TITLE
[Edison] Writing spi in odd bytes causes Edison to go into limbo land

### ISSUE THREAD

**Issue by versamodule** [intel-iot-devkit/mraa#26]
When using SPI in 16 bit mode, and you want to send say 3 bytes you would use 
mraa_spi_write_buf(spi,3); 

If you do this the Edison becomes non responsive. On the scope it just blasts a bunch of data out for a while then quits. The terminal even becomes non responsive. In playing with this I have tried sending 1,3,5,7,9 bytes and they all do the same. Only even numbers work.

**Comment by arfoll** [comment]
This works (and afaik worked for a while). We know support 16bit and odd number of bytes write on edison.
