### ISSUE TITLE
DS18B20 support

### ISSUE THREAD

**Issue by akulo** [intel-iot-devkit/mraa#263]
I would like to see support for One wire DS18B20 Temperature Sensor

**Comment by alext-mkrs** [comment]
There's already 1-wire support request #154, as you've already found out. Specific sensors support is a domain of intel-iot-devkit/upm, which uses mraa underneath.

So to me this looks like a candidate for closure - please continue the 1-wire discussion in #154 and feel free to copy/paste this request to the upm tracker.

**Comment by arfoll** [comment]
Yes this is really a UPM request and look in #154. Feel free to suggest a way that will work generally, I don't know of any ways.
