### ISSUE TITLE
Is SPI working for Minnow Max?

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#267]
Hi,

Wanted to do some testing on Spi and can't initialize the Spi object.

>>> s = m.Spi(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mraa.py", line 1270, in __init__
    this = _mraa.new_Spi(bus)
ValueError: Error initialising SPI bus

no luck with bus no. from 0 to 9

**Comment by arfoll** [comment]
To use spi you have to load spidev, from here: https://github.com/MinnowBoard/minnow-max-extras/tree/master/modules/low-speed-spidev. It's a bug that it's not included in images by default but not a mraa bug :)

**Comment by cosscat** [comment]
Thanks Brendan, I'll have a look
