### ISSUE TITLE
Commit 5c7bab1c79c0d3102d299137335b19f2b632fafe breaks analog input on edison 

### ISSUE THREAD

**Issue by Jon-ICS** [intel-iot-devkit/mraa#280]
Hi,

This commit breaks analog input on edison with the arduino breakout board.  With this patch applied, all analog reads return 0, regardless of the input voltage supplied to the analog pin.  Reverting this patch allows analog input to work again.

**Comment by tingleby** [comment]
5c7bab1c79c0d3102d299137335b19f2b632fafe link for the lazy.
Neglects to consider the ADC.

**Comment by arfoll** [comment]
Thanks for noticing this so fast @Jon-ICS saves @cosscat coming to shout at me tmrw!

**Comment by Jon-ICS** [comment]
No problem! A first, I thought I had fried my arduino breakout board :)
