### ISSUE TITLE
Gpio can be initialized with pin no. that is not I/O

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#286]
Hello,

mraa version: 'v0.7.5-55-g5c7bab1'
```
>>> m.getPlatformName()
'Intel Edison'
>>> i=m.Gpio(15)
>>> i.getPin()
15
>>> i.dir(m.DIR_OUT)
0
>>> m.getPinName(15)
'A1'
```
This should not be possible.

**Comment by arfoll** [comment]
that's normal, AIO pins can be used as GPIOs this way.

**Comment by alext-mkrs** [comment]
You run this on Arduino expansion board, aren't you? If so, that's perfectly ok, on Edison and Galileo gen2 you can use analog pins as GPIOs.

See https://github.com/intel-iot-devkit/mraa/blob/master/docs/edison.md, Arduino board description.

**Comment by cosscat** [comment]
thanks Alext. Good info
