### ISSUE TITLE
mraa broken with node.js v4.1.0

### ISSUE THREAD

**Issue by arfoll** [intel-iot-devkit/mraa#288]
@Propanu affects u too...

**Comment by xbolshe** [comment]
mraa is not broken with node.js v4.1.0. It does not support it because of some function changes. I have a plan to publish my mraa commit tested on node.js v4.1.1 with Galileo board.

**Comment by xbolshe** [comment]
See https://github.com/intel-iot-devkit/mraa/pull/297

**Comment by Propanu** [comment]
Could we ask for your help to check if UPM builds with the changes too?

**Comment by xbolshe** [comment]
Yes, it does. https://github.com/intel-iot-devkit/upm/pull/279

**Comment by xbolshe** [comment]
But need to check for errors:

![someprobs](https://cloud.githubusercontent.com/assets/10796236/10236638/d8eb22a0-68b0-11e5-9655-b0588bcc6498.jpg)

**Comment by arfoll** [comment]
Closed with 3059c06fa05c4a5536ec82d00bd991891956704d by @xbolshe. Thanks a million!
