### ISSUE TITLE
UART flush() not working as expected on Edison

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#289]
Hello,
mraa ver.: 'v0.7.5-55-g5c7bab1'
for uart module:
write something in Putty and then:
```
>>> u.dataAvailable()
True
>>> u.flush() 
0
>>> u.dataAvailable()
True
>>> data=u.read(len(data)) # data is a bytearray
>>> print data
yes

```
I didn't wrote something else in between those two u.dataAvailable() and the flush should have flushed the buffer.

**Comment by arfoll** [comment]
we already went through this on IM but tcdrain() which is what is called by flush() simply blocks until everything is written as writes are async. It does not discard buffers as tcflush() would do. Tbh I'm not sure I like the behaviour but it's whats done in all the other serial libs I've seen :)

**Comment by cosscat** [comment]
yes, you're right. i forgot this one. if it's ok for you i can consider this an exception for Edison
