### ISSUE TITLE
High speed ADC at 8khz or higher?

### ISSUE THREAD

**Issue by sriranjanr** [intel-iot-devkit/mraa#293]
I want to sample audio input at 8khz on ADC0. How shall I get high speed ADC on edison using MRAA?

**Comment by arfoll** [comment]
To sample at that speed you really want to be using a kernel driver on IIO

**Comment by sriranjanr** [comment]
Could you tell me more about how to do it?I am working with microphone for an audio application.I am able to generate sound using fast PWM like given here https://github.com/llatta/edison-audio but I want to use some such similar code to sample ADC at a high speed.
