### ISSUE TITLE
iio: allow device index to be found via device->name

### ISSUE THREAD

**Issue by arfoll** [intel-iot-devkit/mraa#309]

**Comment by alext-mkrs** [comment]
Let me take this one next.

**Comment by alext-mkrs** [comment]
Hmm, interesting that this one is still open even though I've referenced it in the commit, @arfoll, could you please close it?

**Comment by arfoll** [comment]
Maybe because it's not pushed to master? Not sure but closed.

**Comment by tingleby** [comment]
Issue normally only gets actioned on with references when the commit hits master, which kind of makes sense as iio is a feature branch yet in "upsteam" mraa.

**Comment by alext-mkrs** [comment]
Good point, I think that's exactly the case.
