### ISSUE TITLE
Grove LCD display does not display text on Edison

### ISSUE THREAD

**Issue by mmccool** [intel-iot-devkit/mraa#31]
The "Grove-LCD RGB Backlight v2.0" Node.js example code given at 
https://software.intel.com/en-us/iot/sensor/grove-lcd-rgb-backlight
does not work on Edison (I have not tested on Galileo).   

Specifically, the backlight color can be changed, but no text can be displayed on the LCD (these functions are apparently controlled by two different devices at different I2C addresses).

I tried with two separate displays and had the same problem, so I've ruled out the particular display I was using having a problem.   Someone also suggested putting a small delay between the I2C call to set the color and the call to set the display.  This also did not resolve the issue.   In other words, the following code has the same problem:

// Load i2clcd module
var LCD = require('jsupm_i2clcd');
//Initialize Jhd1313m1 at 0x62 (RGB_ADDRESS) and 0x3E (LCD_ADDRESS) 
var myLcd = new LCD.Jhd1313m1(0, 0x3E, 0x62);
myLcd.setColor(64,255,64);
setTimeout(function() {
console.log("Attempting to say hi");
  myLcd.setCursor(0,0);
  myLcd.write('Hello World');  // doesn't work for some reason
  console.log("Done saying hi");
},1000);

I double-checked the I2C addresses and they seem to be correct, but that could be one possible error... if someone else can confirm that would be good.

Looking at the journal the following messages related to mraa appear ("george" is the name of my Edison):
Nov 05 10:30:21 george libmraa[279]: libmraa initialised for platform 2 
Nov 05 10:30:21 george libmraa[279]: libmraa initialised for platform 2 
Nov 05 10:30:21 george libmraa[279]: Invalid i2c bus, moving to default i2c bus 
Nov 05 10:30:21 george libmraa[279]: Invalid i2c bus, moving to default i2c bus

**Comment by BenWillett** [comment]
I had this problem too. Setting the board and shield to 5v solved it. Thanks @mmccool !

**Comment by ToddKlindt** [comment]
I was having the same problem with a Linkit One and a Grove shield. Switching the voltage to 5V fixed it. Thanks.

**Comment by ggodreau** [comment]
Me too. Many thanks @mmccool :bowing_man: 

Note that it seems the latest version of mraa requires you to import the library before the upm stuff, as so:

```
require('mraa');
var LCD = require('jsupm_i2clcd');
var myLcd = new LCD.Jhd1313m1 (0, 0x3E, 0x62);
console.log(myLcd.name());

myLcd.setCursor(0,0);
myLcd.setColor(0, 255, 0);
myLcd.write('Hello World');
```

**Comment by arfoll** [comment]
This seems unlikely... Probably something else at play here... Check syslog
for a hint

**Comment by ggodreau** [comment]
@arfoll here's the output if you don't include mraa:

`Error: Illegal arguments for construction of _exports_Jhd1313m1`

Taken from node_modules/jsupm_grove/README.md:

```
### Usage
Unfortunately, due to the way node-gyp builds MRAA and UPM, the platform
initialization hooks are lost. This means you will have to do it manually,
and require MRAA *before* you load a UPM module:

require('mraa');
var lib = require('jsupm_<module-name>');
```

¯\_(ツ)_/¯

**Comment by arfoll** [comment]
Ah right, building upm with npm is probs not the way I would recommend
doing it...

Wonder if we can fix that quirk though....

**Comment by njk-jeev** [comment]
> Turns out the voltage was set to 3.3V, not 5V. In fact I had both the switch on the shield and the J9 (IOREF) jumper on the board in the 3.3V position due to some earlier work with 3.3V devices. Correcting that fixed the issue. So, summary: when using this display, be aware it won't work at 3.3V. Except as a nightlight.

Thank you, when I change the switch from 3v3 to 5v, I could see the text displayed on LCD screen.
