### ISSUE TITLE
iio_driver.c example printf take extra argument

### ISSUE THREAD

**Issue by laykuanloon** [intel-iot-devkit/mraa#320]
printf("  value = %05f\n", chan->index, (float)res);

**Comment by alext-mkrs** [comment]
@arfoll I wonder if we want to close such ones (living in a separate branch) manually or just wait until it's merged back? Tbh I'd propose to close them after it's on the branch because technically we've fixed it, but what do you think?

**Comment by alext-mkrs** [comment]
078b63 fixes this and is now on master  closing.
