### ISSUE TITLE
build libmraa for Pi and BB

### ISSUE THREAD

**Issue by jiangzidong** [intel-iot-devkit/mraa#329]
If I want to build libmraa for Raspberry Pi and BB, what should I do?
just in ubuntu and `cmake --DBUILDARCH=arm`?

**Comment by arfoll** [comment]
You only need to set the architecture like that if you are cross compiling
or forcing it. If you are compiling on the target then it will detect the
arch.

**Comment by tingleby** [comment]
@arfoll no if during the cmake setup it sees a compatible arch, will it not set to that. So if you use gcc-arm it will automatically select arm platforms? The forcing is mainly a testing feature.

**Comment by mulderp** [comment]
Also, it might be to see the commands to fetch dependencies before running a build. E.g. for Yocto distributions, there are these commands:

    echo "src mraa-upm http://iotdk.intel.com/repos/1.1/intelgalactic" > /etc/opkg/mraa-upm.conf
    opkg update
    opkg install libmraa0

But on RPi or BB one would probably use some kind of "apt-get" commands?

**Comment by leonyuhanov** [comment]
I wrote up a step by step guide here
http://www.elec-tron.org/?p=996

**Comment by arfoll** [comment]
@mulderp our instructions are only valid for iot devkit images galileo/edison/minnowboard max, probabyl should make this clearer

**Comment by jiangzidong** [comment]
Thanks, I will close the issue for now.
