### ISSUE TITLE
SPI: JavaScript, SPI.write function prototype

### ISSUE THREAD

**Issue by xbolshe** [intel-iot-devkit/mraa#330]
JavaScript, Node v4.1.1,  mraa/examples/javascript/spi.js

SPI.write prototype:
uint8_t * write (uint8_t *txBuf, int length)

NodeJS code:
x = new m.Spi(0)
buf2 = x.write(buf)
console.log("Sent: " + buf.toString('hex') + ". Received: " + buf2.toString('hex'))

Question: what is an output of the function: received data length or received data buffer ?

**Comment by arfoll** [comment]
received data buffer - is it not working as you'd expect?

**Comment by xbolshe** [comment]
Yes, an output is a noise, but it shall be as an input.
I have checked kernel driver and libmraa - no problem.
The problem is in mraajs.i
![spijs_before](https://cloud.githubusercontent.com/assets/10796236/10680136/bcdfb276-7925-11e5-9841-2e9dbe48341b.jpg)

**Comment by xbolshe** [comment]
BTW, mraajs.i has the following code:

namespace mraa {
class Spi;
%typemap(out) uint8_t*
{
%#if SWIG_V8_VERSION > 0x040000
   v8::MaybeLocal<v8::Object> objret = node::Buffer::New(v8::Isolate::GetCurrent(), (char*) $1, arg3);
   free($1);
   if(!objret.ToLocal(&$result)) {
      SWIG_exception_fail(SWIG_ERROR, "Spi buffer failed");
      SWIGV8_RETURN(SWIGV8_UNDEFINED());
   }


Please pay your attention for %typemap(out) uint8_t*
It is not a buffer!

**Comment by xbolshe** [comment]
https://github.com/intel-iot-devkit/mraa/pull/332

**Comment by xbolshe** [comment]
With changes I have:

![spijs_chk](https://cloud.githubusercontent.com/assets/10796236/10680928/f99d6bca-792c-11e5-91c6-8ba61fe10757.jpg)

**Comment by xbolshe** [comment]
And need to add free(result); to free uint8_t* recv = malloc(sizeof(uint8_t) * length); from mraa_spi_write_buf
