### ISSUE TITLE
Working with JS callbacks

### ISSUE THREAD

**Issue by mulderp** [intel-iot-devkit/mraa#339]
Hi,

just curious about why there are no callbacks used in the JavaScript examples.
I am looking at using an input button: When it is pressed, a callback should be executed, e.g.:

      var button = new mraa.Gpio(4);
      button.dir(mraa.DIR_IN);

      button.read(function(d) {
          if (d==1) {
            console.log('ON');
          } else {
            console.log('OFF');
          }
      }, sampleRate);

Would something like this be possible?

**Comment by mulderp** [comment]
My current code is:

```
    setInterval(function() {
      var input = button.read();
      console.log(input);
    }, sampleRate);
```

But to detect very fast clicks, sampleRate is e.g. 100ms - so, I was thinking it might be nice to have a callback that is called whenever the button is pressed, without "polling" in setInterval or another kind of loop.

**Comment by FlippieCoetser** [comment]
@mulderp  you can configure an Interrupt that has a callback. That way you don't have to loop and read the value continuously. You can further specify when the callback is triggered: On button press or on button depress. Depending on your application you might also have to implement some denouncing hardware or software.

**Comment by mulderp** [comment]
Exactly what I am looking for! Thanks! How would I attach/map an interrupt to a Gpio pin?

**Comment by FlippieCoetser** [comment]
Their is a function called ISR that you can use to configure the interrupt. Just watch out not all pins can be used with interrupts. Check the documents for more details on the ISR func.

**Comment by mulderp** [comment]
right, there is even an example for that:

https://github.com/intel-iot-devkit/mraa/blob/master/examples/javascript/isr.js

thanks!

**Comment by mulderp** [comment]
works great:

```
var mraa=require('mraa');


function h() {
  console.log("hello");
}


p = new mraa.Gpio(4);
p.isr(mraa.EDGE_FALLING, h);

setInterval(function() {
  console.log("h");

}, 400);

```
