### ISSUE TITLE
Uart python example

### ISSUE THREAD

**Issue by BTWS** [intel-iot-devkit/mraa#376]
Is it possible to provide a more elaborate example for uart in python?

**Comment by alext-mkrs** [comment]
Definitely! Do you have any specific scenario or use cases in mind?

**Comment by BrechtW** [comment]
Communicating with a Dynamixel servo to be specific. This requires features like only writing when the input buffer isn't full. Setting baudrate, timeout, flush, read, write.

**Comment by alext-mkrs** [comment]
Ok, thanks. I don't have such a servo, but the information you've provided is enough for me to get the idea.
