### ISSUE TITLE
There is no MRAA change log

### ISSUE THREAD

**Issue by xbolshe** [intel-iot-devkit/mraa#388]
There is no MRAA change log. UPM has a change log :)

**Comment by xbolshe** [comment]
Probably need to separate a change log from https://github.com/intel-iot-devkit/mraa/blob/master/docs/index.md to a single file.

**Comment by xbolshe** [comment]
And need to add news in the version 0.9.0

**Comment by arfoll** [comment]
I quite like the changelog on front page though see #216. Yes I forgot to do a news for 0.9.0 I'll fix that at some point. I guess doing it the way upm has it wouldn't be so bad....

**Comment by xbolshe** [comment]
https://communities.intel.com/thread/96658
