### ISSUE TITLE
cmake FindNodejs module should indicate that required include files have not been detected 

### ISSUE THREAD

**Issue by whbruce** [intel-iot-devkit/mraa#410]
When the cmake option `BUILDSWIGNODE` is set, the `FindNodejs` cmake module is used to detect the presence of packages requires to build the Javascript binding. The current logic looks for the include files but no action is taken if they are not found. Thus the g++ include path is invalid and the build fails (can't find `node.h`). I hit this problem as package `nodejs` was installed but `nodejs-devel` was not.

I can update the `FindNodejs` cmake module to catch this condition and flag an error but wanted to check if current behavior was required before proceeding. 

Let me know.

**Comment by alext-mkrs** [comment]
This was implemented by PR #414 for a while now - closing this one.
