### ISSUE TITLE
mraa packages 0.9.1-0.9.4 are not published to intelgalactic 2.0 repo, should we use 3.0?

### ISSUE THREAD

**Issue by alext-mkrs** [intel-iot-devkit/mraa#444]
Looks like starting from 0.9.1 packages are being uploaded to http://iotdk.intel.com/repos/3.0/intelgalactic instead of 2.0 they used to be in.

Should we update the readme.md, which still points to 2.0?

**Comment by arfoll** [comment]
Yeah we should I forgot, thanks for pointing that out

**Comment by alext-mkrs** [comment]
Ok, the PR is in.

**Comment by arfoll** [comment]
Closed with PR
