### ISSUE TITLE
MRAA docs for enum Mode

### ISSUE THREAD

**Issue by thoughtentity** [intel-iot-devkit/mraa#455]
I was reading through the [docs](http://iotdk.intel.com/docs/master/mraa/node/classes/common.html#enum_Mode) for MRAA and noticed something odd in the table describing the enum for Mode. The docs describe the enum Mode as follows:

Enum | Description
---------|---------------
MODE_STRONG  | Default. Strong high and low.
MODE_PULLUP | Interrupt on rising and falling.
MODE_PULLDOWN | Interrupt of rising only.
MODE_HIZ | Interrupt of falling only.

Shouldn't the descriptions for `MODE_PULLUP`, `MODE_PULLDOWN` and `MODE_HIZ` be describing configuring the GPIO pin with an internal pull up, internal pull down or hi-z (high impedance) state, respectively?

**Comment by arfoll** [comment]
Indeed some poor copy & paste there.

Thanks for the catch and report!
