### ISSUE TITLE
Bad error return type

### ISSUE THREAD

**Issue by wda2945** [intel-iot-devkit/mraa#480]
mraa_i2c_write() has a return type of mraa_result_t which is an enum of positive values (or zero).

mraa_i2c_write() makes a tail call of `return mraa_i2c_smbus_access()`.

mraa_i2c_smbus_access() makes a tail call of `return ioctl()`

ioctl() returns -1 on error, or otherwise a value certainly not within the mraa_result_t enum.

**Comment by arfoll** [comment]
Thanks for reporting this!
