### ISSUE TITLE
[Edison Arduino] mraa(for js) fail after press "reset" button in Edison/Arduino

### ISSUE THREAD

**Issue by ddnionio** [intel-iot-devkit/mraa#49]
when i press the reset button (SW1u15) on edison arduino board, the system will reboot and then the mraa fails. (type reboot in yocto or press power button on board are both fine to mraa, only press reset will result in failure)

the blink example can not "blink" the led, sometimes the error message is as follows
Failed to write to export
Intel Edison Failed to initialise Arduino board TriState,                         check i2c devices! FATAL
Failed to write to export
Intel Edison Failed to initialise Arduino board TriState,                         check i2c devices! FATAL
Segmentation fault

and when I tried to new m.Gpio(5), it shows "Illegal arguments for construction of _exports_Gpio"

mraa will become normal only when I cut off the board power and re-supply it

**Comment by alext-mkrs** [comment]
Looks like I'm observing something very similar right now on my board, however it's not related to the Reset button (i.e. happens if I `reboot` or power it off as well).

And looks like it fails at testing whether it's an Arduino expansion board (it actually is) by trying to initialize GPIO 214 and I see this check is there for quite a while in the code, so it must work. There also were no changes to the `gpio.c` code that handles the pin init itself since I tried it last time (mid-December), so to be honest I'm out of ideas as to the reason.

Below is the strace output (library binary is compiled from current master):
```
open("/sys/devices/virtual/dmi/id/board_name", O_RDONLY) = 4
fstat64(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb77a8000
read(4, "BODEGA BAY\n", 4096)           = 11
stat64("/sys/class/gpio/gpio214/", 0xbfea74c0) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 5
write(5, "214", 3)                      = -1 ENODEV (No such device)
time(NULL)                              = 1422204815
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 6
fstat64(6, {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
fstat64(6, {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb77a7000
read(6, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0UTC\0\0\0TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0UTC\0\0\0\nUTC0\n", 4096) = 118
_llseek(6, -6, [112], SEEK_CUR)         = 0
read(6, "\nUTC0\n", 4096)               = 6
close(6)                                = 0
munmap(0xb77a7000, 4096)                = 0
send(3, "<139>Jan 25 16:53:35 libmraa[423]: gpio: Failed to write to export", 66, MSG_NOSIGNAL) = 66
close(5)                                = 0
close(4)                                = 0
munmap(0xb77a8000, 4096)                = 0
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb77a8000
write(1, "hello mraa\n", 11hello mraa
)            = 11
write(1, " Version: v0.5.4-100-g6c73a8a\n", 30 Version: v0.5.4-100-g6c73a8a
) = 30
write(1, " Running on Intel Edison\n", 25 Running on Intel Edison
) = 25
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by alext-mkrs** [comment]
Looks like there was a [similar report](https://communities.intel.com/thread/59649) in the Intel's Edison Community as well, so I've asked Intel tech support folks to report that to the Edison dev team and referenced this bug record. IMHO that doesn't look like mraa fault, rather like something more generic, so worth an investigation.

**Comment by arfoll** [comment]
This has been addressed in the ww5 release note as a platform issue. Closing as HW/platform bug not under our control.

**Comment by WoodyWoodsta** [comment]
Hi guys. I know that this is a long lost issue, however, I'm having this issue currently (using `johnny-five` and `edison-io`).

I understand that this is a platform issue, but is there a way to recover functionality after having pressed the reset button by mistake? I cannot afford to have to reflash the system each time the button it pressed.

**Comment by arfoll** [comment]
Yes, just do a full power cycle, remove all power, wait a few seconds and start again. Should be all good

**Comment by WoodyWoodsta** [comment]
Half a day, and all it was was the power. :laughing: Thanks for the help :+1:
