### ISSUE TITLE
Recent MRAA i2c bus 0 is no longer valid on edison

### ISSUE THREAD

**Issue by jontrulson** [intel-iot-devkit/mraa#497]
With recent MRAA (5e867419bc0dd7c7ece48522ae1759de45812445) attempting to use i2c bus '0' on edison with the arduino breakout fails with the following in the syslog:

>Apr 25 23:49:07 edison libmraa[400]: edison: Arduino board detected
>Apr 25 23:49:07 edison libmraa[400]: libmraa initialised for platform 'Intel Edison' of type 2
>Apr 25 23:49:07 edison libmraa[400]: i2c_init: Selected bus 0
>Apr 25 23:49:07 edison libmraa[400]: i2c0_init: Invalid i2c bus

Previously this would switch to the proper bus 6 on edison.  This no longer seems to occur, and will break a lot of UPM drivers.

**Comment by arfoll** [comment]
thanks for the report, this has been rollbacked.
