### ISSUE TITLE
All npm installs of 1.2.x failing

### ISSUE THREAD

**Issue by jakehewitt** [intel-iot-devkit/mraa#559]
npm install was failing for 1.2.0 and 1.2.1 due to the previously mentioned ```fatal error: json-c/json.h: No such file or directory```. npm install is successful for 1.2.2 but when the package is actually imported throws an error ```<ommited>/node_modules/mraa/build/Release/mraa.node: undefined symbol: mraa_init_json_platform```

System is running node 6.3.1, npm 3.10.3 on a debian image. Last working version of MRAA was 1.1.2

**Comment by arfoll** [comment]
Urgh sorry about this. For some reaosn my system lets me get away with this, this is the problem we have with so many different combinations. This will be fixed in an hour or so.

**Comment by arfoll** [comment]
1.2.3 is out and hopefully fixes this for you (works here). Travis builds have been updated to make sure this doesn't happen, they know check the npmpkg builds and loads.

**Comment by jakehewitt** [comment]
Wow that was quick, yeah 1.2.3 fixed it
