### ISSUE TITLE
When building with -Wall, there are many warnings that should probably be looked at

### ISSUE THREAD

**Issue by jontrulson** [intel-iot-devkit/mraa#577]
Aside from the multiple java and swig related warnings, there are some (I think) more serious ones like:

`mraa/src/mraa.c:956:9: warning: statement with no effect [-Wunused-value]`
`         for (i; i < num_i2c_devices; i++) {`
**(note the first i)**

There are also lots of unused variables, like this one which wastes 28 ints:
`mraa/src/x86/intel_minnow_byt_compatible.c:92:35: warning: unused variable 'max_pins' [-Wunused-variable]`
`     int uname_major, uname_minor, max_pins[28];`
**(max_pins[28] is marked as unused)**

And others that complain about functions not returning a value as they should (control reaches end of non-void function), etc...

Perhaps, compiling with _-Wall_ should be the default to catch these kinds of things?

Note these are just a couple of the few dozen I captured here.

**Comment by arfoll** [comment]
I'm not a huge believer of such warning fixing (any compiler optimisation will just remove those 28bits for example) but they are starting to stack up and looking a bit ugly. Thanks for taking the time to document it, I've tried to fix the glaring silly ones.

122cab1f1e53b7c9c7cd82905b962071f9bad9dc enables many error checking flags by default. Hopefully adding many more warnings like these will stop them adding up.

SWIG errors are pretty minimal, python2 has one about _POSIX_C_SOURCE but when I looked at it there's not much we can do about it, that's defined twice, our use of syslog screws us over there. Everything else is clean (python3, nodejs) so we just have java errors which haven't been cleaned up but I'll let people who know java better than me sort those out ;-)
