### ISSUE TITLE
[deb] mraa deb pkg

### ISSUE THREAD

**Issue by arfoll** [intel-iot-devkit/mraa#60]
We should support the making of a deb pkg for submission into debian repos.

**Comment by g-vidal** [comment]
Hi,

I don't know if it is the right place to submit this comment... sorry if it is so.
Last week I have built a deb package without any problem, today I am getting an error message that I cannot debug. I am using a RaspBerry Pi3 with debian stretch distribution installed.

I am compiling the last version of node and swig before dealing with mraa. `mraa` compilation and standard installation is OK, `ipk` package generation is OK but it fails for `deb` package. I have also checked with checkinstall that also fails.

Here are the commands and traces :

```shell
mkdir build
cd build
cmake -DIPK=ON -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install 
sudo make package
.[ 22%] Built target mraa
../...
[100%] Built target I2c-compass
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: mraa
CPack: - Install project: mraa
CPack: Create package
CPack: Package mraa_1.3.0.17_armv7.ipk generated.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Makefile:105 : la recette pour la cible « package » a échouée
make: *** [package] Abandon
```
I am trying to maintain a stretch image with mraa and upm for raspberry Pi3 ant that would help a lot to be able to build deb package. Thanks for any help.
Best regards

**Comment by tingleby** [comment]
The IPK generation feature in the build system is a bit rusty and isnt really used that much any more.
A better way to create the DEBs it to use the debian build system 

https://launchpad.net/~mraa/+archive/ubuntu/mraa/+files/mraa_1.3.0-2.debian.tar.xz
Is a copy of the latest debain/* files that is used for the PPA. These should work for Debain too.

**Comment by arfoll** [comment]
We simply don't support building DEBs in this way. Packaging mraa in this way is really not recommended. Using the packages from our ubuntu PPA are a much better starting point.

**Comment by g-vidal** [comment]
OK 
Thanks for the quick answer and great work. I'll try to adapt myself to this evolution... for the moment we will use the original git sources.
