### ISSUE TITLE
Intel System Studio IoT for Windows 404 page (not an mraa issue)

### ISSUE THREAD

**Issue by claytongulick** [intel-iot-devkit/mraa#622]
Hi Intel folks, I know this is only loosely related to mraa, but I can't use mraa or develop until it's resolved.

There's currently no way to download the Intel System Studio IoT for Windows, and hasn't been for a while now, following the links just gives a 404. I've tried leaving messages in the communities section, but haven't had any response.

I'm pretty sure Intel doesn't want 404's on their public site, especially for IoT right now, so I'm just trying to bring this to anyone's attention. Sorry about the github issue in the wrong place, but is there any way you could send an email to the correct folks to get the download working again? Thanks!!

**Comment by arfoll** [comment]
Have you tried just grabbing the installer here:
https://software.intel.com/en-us/iot/hardware/joule/downloads
or:
https://software.intel.com/en-us/iot/hardware/edison/downloads

All seems to work?

**Comment by arfoll** [comment]
Closing as no update

**Comment by claytongulick** [comment]
Thanks @arfoll, I checked and the download is working again. For several days, it was broken and giving a 404. Thanks again!

**Comment by arfoll** [comment]
No worries, I've shared your findings with our sysadmin team. Thanks for
notifying us and we'll try do better!
