### ISSUE TITLE
mraa_pwm_close( ) doesn't close duty file

### ISSUE THREAD

**Issue by vinugk** [intel-iot-devkit/mraa#669]
The mraa library api mraa_pwm_close( ) seems to be not working. It returns success, however the file descriptor is not freed. I have a requirement of init and close the pwm a number of times. With the close function not working i find that Intel Edison ends up in memory leakage. Please help

**Comment by alext-mkrs** [comment]
Which descriptor do you mean? I've just scanned through the code and I don't see anything like that (with a disclaimer that I did that on my phone, which is not the best tool for the job, but all I have right now).

**Comment by vinugk** [comment]
mraa_pwm_init( ) creates a file handler whenever called. This file handler normally should have been closed by mraa_pwm_close( ). However this is not happening, which means every time mraa_pwm_init() is called a new file handler is created and results in memory leakage

**Comment by alext-mkrs** [comment]
Ok, so what you actually mean is mraa_pwm_setup_duty_fp(), which opens the duty sysfs file and indeed that one is never closed. That's a bug, marking as such.

**Comment by vinugk** [comment]
Thanks @alext-mkrs . Is this a known issue? Are there any possible workarounds or fixes available?

**Comment by alext-mkrs** [comment]
Nope, it's not a known one, your report is the first one. There's no workaround I can think of, but just fixing it should be fairly trivial. If no one beats me to it, I plan to prepare a fix tomorrow.
