### ISSUE TITLE
bindings for Lua

### ISSUE THREAD

**Issue by edbek** [intel-iot-devkit/mraa#677]
When can we expect bindings for Lua?

**Comment by arfoll** [comment]
The PR here has been left behind a little: https://github.com/intel-iot-devkit/mraa/pull/527. If it's updated I would merge it.

**Comment by alext-mkrs** [comment]
Actually, we already have #567 for tracking this on the issue side (+a pull request #527 for the implementation itself) - so let me close this one as a duplicate.
