### ISSUE TITLE
How good is libmraa support in coming days?

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [intel-iot-devkit/mraa#769]
Looks like Intel is dropping out of SBC space (not sure though), if that happens will libmraa be continued?

**Comment by arfoll** [comment]
I am not qualified to answer any questions on Intel's current, future plans on SBCs or upcoming platforms. However I will point out that there are plenty of Intel based SBC boards such as Up/Up2/minnowboard max/turbot and I doubt the apettite for such a market will go away any time soon.

There are no plans to ramp down libmraa & UPM, if anything we're seeing adoption growing.
