### ISSUE TITLE
gpio push-pull/open-drain configuration

### ISSUE THREAD

**Issue by NickBridge** [intel-iot-devkit/mraa#774]
Hi All,

what do you think about adding an API to configure output mode (push-pull/open-drain) of GPIOs?

**Comment by arfoll** [comment]
Generally that would be great, there's already been work to add input pull-up/down modes which I will merge soon, https://github.com/intel-iot-devkit/mraa/pull/768

**Comment by arfoll** [comment]
Merged from ML Thanks!
