### ISSUE TITLE
See this commit on adafruit gpio

### ISSUE THREAD

**Issue by nicola-lunghi** [intel-iot-devkit/mraa#776]
https://github.com/adafruit/Adafruit_Python_GPIO/pull/68

sadly they won't respond...

**Comment by arfoll** [comment]
@Propanu do you know anyone at adafruit?

**Comment by nicolalunghiemutex** [comment]
They still don't respond is a pity

**Comment by alext-mkrs** [comment]
Looks like the original issue in the Adafruit repo was closed - I'm closing this one as well, as it anyway wasn't something we could fix at our side.
