### ISSUE TITLE
custom BBB yocto image spidev1.1

### ISSUE THREAD

**Issue by mgiaco** [intel-iot-devkit/mraa#781]
Hi,

How should my json look like if i want to use my spi device under libmraa. I tried to use spidev python package and i figured out that it works. So I think it should also work under mraa. My problem is i only have a spidev1.1. So I tried to check why my yocto build uses 1.1 for that but I did not found any hint till now.
this was my test code:

```python
import spidev
import time


spi = spidev.SpiDev()
print(spi)
ret = spi.open(1, 1)
print(ret)

spi.max_speed_hz = 5000
spi.mode = 0b01

to_send = [0xaa, 0x55, 0xaa, 0x55]
while True:
    spi.xfer(to_send)
    print("xfer")
    time.sleep(0.1)
```
I have used  a logic analyzer and everything looks fine. But I want to use libmraa because I also use it for I2C and the IO´s.

So now I am not sure how the platform entry should look like for that device. So I need bus=1 device=1

```json
  "SPI": [
    { "index":0, "bus": 1, "default": true}
  ]
```
Should I add the miso, mosi... stuff ... because the devices are already set in the dev tree?
If so I am rigth that I have add the line as normal GPIO first with the correct rawpin number and than use the index of the gpio for the pin number of the SPI setting.

many thanks

**Comment by mgiaco** [comment]
@alext-mkrs  hi, many thank. Sure I used the documentation and the examples as a starting point. So from the example here. This means mraa uses spidev0.0 right? and as an example the clock pin is gpio 11 which is definded as lable   {"label": "SPI_CLK"},  so but there is no mapping to a rawpin so the pin is used from the dev tree - right? 

  "SPI": [
    { "index":0, "bus": 0, "slaveselect": 0, "clock": 11, "miso": 7, "mosi": 9, "chipselect": 5, "default": true}
  ],

**Comment by alext-mkrs** [comment]
So it goes like this:
1. `bus` is an SPI bus number, i.e. if you have `/dev/spidev5.1`, that would be 5.
1. `slaveselect` is the slave/chip select number from spidev, i.e. in the above case that would be 1. mraa constructs the spidev filename to talk to using "spidev<bus>.<slaveselect>" string.
1. `clock`, `miso`, `mosi` are pins for respective functions, numbers are in pin indexes, not raw pin numbers. These aren't used directly as mraa uses spidev to do the necessary communication, this is more for the accounting.
1. `chipselect` is a pin, which will be used as a "software" CS in GPIO mode, if specified. If provided, should be again in terms of pin indexes, not raw.

**Comment by mgiaco** [comment]
@alext-mkrs 
many thanks. I think that should go to the docs.

**Comment by alext-mkrs** [comment]
Glad to help. Yeah, I've noticed the docs could do with some elaboration and submitted #784 for that
