### ISSUE TITLE
Links to Python documentation broken

### ISSUE THREAD

**Issue by ukBaz** [intel-iot-devkit/mraa#806]
The Python and Java links at:
https://github.com/intel-iot-devkit/mraa#api-documentation
are not working for me

**Comment by arfoll** [comment]
@tingleby you broke DNS! Can you take a look?

**Comment by arfoll** [comment]
@ukBaz btw real link is here: https://iotdk.intel.com/docs/master/mraa/python/

@tingleby updated some DNS entries the other day, this must be a mistake.

**Comment by tingleby** [comment]
Whoops missed this. *Should* be good again!
