### ISSUE TITLE
edison - spi read error

### ISSUE THREAD

**Issue by IoTboy** [intel-iot-devkit/mraa#82]
Issue reading from spi returns  a copy of the content of the write buffer in the read buffer, though the data on receive line is different. 

Please refer https://software.intel.com/en-us/forums/topic/537676 for more info.

**Comment by KurtE** [comment]
Not enough information here to look at. Like what arfoll mentioned.  No code fragment to look at?
Is it related to this thread? https://communities.intel.com/thread/58728

**Comment by arfoll** [comment]
Closed due to lack of information.
