### ISSUE TITLE
cmake ..

### ISSUE THREAD

**Issue by silver2row** [intel-iot-devkit/mraa#823]
Hello,

I am trying to build with cmake and it is not working. I have a BeagleBone Green Wireless. I can access the sudo mraa-gpio list cmd in the terminal but I can only do that one cmd.

I have some issues. I installed cmake and I do not know if the sudo mraa-gpio list cmd is a key to knowing if the build worked. 

Seth

**Comment by silver2row** [comment]
Hello Again,

I will have the error messages posted soon. Sorry for the delay.

Seth

**Comment by silver2row** [comment]
Hello...my error codes are located here: https://github.com/intel-iot-devkit/mraa/issues/821. 

I accidentally erased the post and then reopened it. Sorry for the oddness.

Seth

P.S. Let a brother know what is going on during my build. If you need any info, just let me know.

**Comment by arfoll** [comment]
I'll close this one - let's carry on in #821
