### ISSUE TITLE
What is iio_driver.c ?

### ISSUE THREAD

**Issue by metropt** [intel-iot-devkit/mraa#824]
I was reading the examples and doesn’t found any information about what iio_driver is.

Thank you

**Comment by arfoll** [comment]
It's meant to be a generic example for interfacing with an IIO driver. I think it worked with iio_dummy so that we could test the API and that exposed an accelerometer.

**Comment by alext-mkrs** [comment]
Seems to be answered - so closing. Feel free to comment if this needs to be reopened.
