### ISSUE TITLE
how to control the TPS65217 on the beaglebone? ... not a real mraa question..

### ISSUE THREAD

**Issue by mgiaco** [intel-iot-devkit/mraa#840]
I search for some information about how to control the TPS65217 on the beaglebone black. Is here anyone who is already using this. So my goal is to detect from python if I am battery powered or not.

many thanks
cheers
mathias

**Comment by arfoll** [comment]
Uhm no idea sorry, you'd probably have more luck on a BBB focused forum or
IRC channel

**Comment by mgiaco** [comment]
many thanks
