### ISSUE TITLE
I am wondering if someone already used or using Nuitka for python and mraa

### ISSUE THREAD

**Issue by mgiaco** [intel-iot-devkit/mraa#844]
Hi,

I do have some performance problems with my app on the BeagleBoneBlack. I use python 2.7 and I do use mraa and upm a lot. So I am wondering if it would be possible to use Nutika http://nuitka.net.
So before I try I taught I will ask here if someone already tried that?

many thanks

**Comment by arfoll** [comment]
Sorry I've never heard of people using it. But sounds interesting, would
love to hear if it works for you!

**Comment by mgiaco** [comment]
okay many thanks. I will try it maybe... i will report here.
