### ISSUE TITLE
How could I remove mraa and install it again?

### ISSUE THREAD

**Issue by Mohamad777** [intel-iot-devkit/mraa#848]
I've changed some files of the library manually, so I've problem with mraa now.

How could I remove mraa and install & build it again?

**Comment by arfoll** [comment]
Just run make install again? It'll wipe all the old libs and headers.

**Comment by Mohamad777** [comment]
It didn't work.
I've removed /usr/lib/arm-linux-gnueabihf/libmraa.so file and now it is not available even after make install again.
And I get this error in run time:
error while loading shared libraries: libmraa.so.1: cannot open shared object file: No such file or directory

I'm using Ubuntu mate on RPI3.

**Comment by alext-mkrs** [comment]
Are you sure `make install` succeeds? If you could post a console log for the whole process, that could be helpful for understanding what's going on. The process is way to simple to break :), so I wonder what could've gone wrong there.

**Comment by alext-mkrs** [comment]
@Mohamad777, is this still relevant, do you need any further help?

**Comment by alext-mkrs** [comment]
Closing for no response, feel free to comment if help is still needed.

**Comment by jinglong485** [comment]
Hi,

Can I usr make uninstall to remove mraa?
