### ISSUE TITLE
How I can crosscompile new version of mraa for linkit 7688

### ISSUE THREAD

**Issue by Ladeia** [intel-iot-devkit/mraa#849]
Hello,

My linkit have one old version of lib mraa 0.8, but I need compile atual version for linkit, but I cant see the document for crosscompile.

Someone can help-me?

**Comment by alext-mkrs** [comment]
Generally, as we use cmake, that's no different than cross-compiling any cmake-based project. Specifics depend on your toolchain and environment. Is that just a plain compiler/linker/etc set, or something more complex like Yocto? If the former and you have so called toolchain file, you can feed it into cmake and it should do it automagically. For yocto you can use an existing recipe from meta-oe. Describe what you have (if that's freely downloadable - share a link, I'll take a look) and I may be able to advise more specifically.

**Comment by alext-mkrs** [comment]
@Ladeia, does my answer help? Do you need any further assistance with this one?

**Comment by Ladeia** [comment]
Sorry for delay, I migrate the project for LEDE OS and now I can compile the project :-)

**Comment by vanbwodonk** [comment]
Hi how do you compile it on LEDE? i try but i can make it works, help me please

this is my  feeds for linkit use LEDE, i can compile it without mraa & upm.
https://github.com/vanbwodonk/lks7688-LEDE-feeds

**Comment by shmrymbd** [comment]
hi @Ladeia could you help how to compile lede with latest mraa and upm? @vanbwodonk
