### ISSUE TITLE
Any plans to support TinkerBoard S

### ISSUE THREAD

**Issue by mgiaco** [intel-iot-devkit/mraa#854]
Hi,

Are there any plans to support the new Tinker Board S?

https://www.asus.com/Single-Board-Computer/Tinker-Board-S/#tinker-board-kv-info

many thanks
mathias

**Comment by arfoll** [comment]
Hi Mathias,

Looks like a nice board, I wasn't aware of it - I'm not sure anyone has looked into adding support but we would happily help anyone do the platform support and include the patch into master without any reservations.

On a sidenote, this benchmark with 'competitor SBC' made me laugh :)
![image](https://user-images.githubusercontent.com/514406/35052730-9ed0c844-fba8-11e7-802d-2176ec8743b7.png)

**Comment by mgiaco** [comment]
okay the bad thing is it doesn´t have a PRU.
