### ISSUE TITLE
break missing in mraa.c - mraa_pin_mode_test

### ISSUE THREAD

**Issue by michael-ring** [intel-iot-devkit/mraa#86]
I found out that a break before the default case is missing in mraa_pin_mode_test.

The result of this bug is that I get a log entry in syslog even though all is OK:

Jan  5 23:22:36 beaglebone libmraa[2380]: requested pinmode invalid

adding a break statement fixes that:

ring@beaglebone:~/devel/mraa/src$ git diff mraa.c
diff --git a/src/mraa.c b/src/mraa.c
index 70be118..3b4bc34 100644
--- a/src/mraa.c
+++ b/src/mraa.c
@@ -263,6 +263,7 @@ mraa_pin_mode_test(int pin, mraa_pinmodes_t mode)
         case MRAA_PIN_UART:
             if (plat->pins[pin].capabilites.uart == 1)
                 return 1;
+            break;
         default:
             syslog(LOG_NOTICE, "requested pinmode invalid");
             break;

**Comment by arfoll** [comment]
Thanks alot for reporting @michael-ring!
