### ISSUE TITLE
Up Squared - Nodejs on Ubuntu: How to compile?

### ISSUE THREAD

**Issue by lenhuy** [intel-iot-devkit/mraa#871]
1. Test.js
var m = require('mraa');
console.log("MRAA version: " + m.getVersion());
var digitalPin = new m.Gpio(12);

2. node Test.js

MRAA version: v1.9.0
Test.js:3
var digitalPin = new m.Gpio(12);
                         ^
Error: Illegal arguments for construction of _exports_Gpio

3. sudo node Test.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'mraa'

**Comment by Propanu** [comment]
Use `sudo -E node Test.js`, or modify your `sudoers` file to keep `NODE_PATH`.

**Comment by lenhuy** [comment]
1. sudo -E node Test.js
Got the same error same "node Test.js"

MRAA version: v1.9.0
Test.js:3
var digitalPin = new m.Gpio(12);
                         ^
Error: Illegal arguments for construction of _exports_Gpio

2. How do I modify sudoers file to keep NODE_PATH?

**Comment by alext-mkrs** [comment]
@lenhuy, you can find many tutorials/guides on configuring `sudo` using your favorite search engine, as this is a standard Linux tool. It's strange that `sudo -E` didn't work. Please post the contents of your system syslog/journal around the time you run this, mraa should be logging more details there.

**Comment by Propanu** [comment]
Are you using the Ubuntu [image](https://downloads.up-community.org/download/up-squared-iot-grove-development-kit-ubuntu-16-04-server-image/) provided by Emutex for the UP2, or just plain vanilla Ubuntu? The latter won't give you access to the GPIO pins as it doesn't have the required kernel driver.

**Comment by Propanu** [comment]
You can find instructions on how to patch the kernel here: https://wiki.up-community.org/Ubuntu

**Comment by lenhuy** [comment]
I'd would like to use GrovePi board for the Up Squared, which packets that I need to install?

**Comment by lenhuy** [comment]
I got it working now. Need the line below to interface with Grove Sensors.
mraa.addSubplatform(mraa.GROVEPI, "0 ")
