### ISSUE TITLE
build fails on DragonBoard410 with SWIG

### ISSUE THREAD

**Issue by ric96** [intel-iot-devkit/mraa#874]
Builds have been failing on the db410c running Debian Buster release with Swig 3.0.12 and node v8.9.3
Builds fine by disabling swig -DBUILDSWIGNODE=OFF.
Build log: https://paste.ubuntu.com/p/Spmk8qszJN/

**Comment by arfoll** [comment]
You have a very recent version of node.js. So you will need to patch swig: https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-devtools/swig/swig/0001-Add-Node-7.x-aka-V8-5.2-support.patch

**Comment by alext-mkrs** [comment]
As this is a known dependency problem and not mraa itself + @arfoll has provided a solution - I'm closing this one.
