### ISSUE TITLE
mraa mock platform interacts with underlying hardware

### ISSUE THREAD

**Issue by malikabhi05** [intel-iot-devkit/mraa#879]
The mraa mock platform interacts with the underlying hardware while calling the function `mraa_get_number_of_gpio_chips()` in `src/gpio/gpio.c:mraa_gpio_chardev_init`, returning the number of gpio chips available on the underlying hardware for the mock platform.

And then eventually further down  `mraa_get_chip_info_by_number()` fails returning NULL.

**Comment by alext-mkrs** [comment]
That's an interesting one - sounds like when adding those chardev-related functions necessary _replace overrides were not added for the mock platform. I'll look into this on the weekend if I have time.

**Comment by Propanu** [comment]
No need to, my chardev patch should fix this.

**Comment by Propanu** [comment]
@malikabhi05 does this work as expected now?

**Comment by malikabhi05** [comment]
yes, it seems to work as expected now. closing it.
