### ISSUE TITLE
MRAA - SWIG 4.0 - .NET Core 2.1 C# - arm64v8

### ISSUE THREAD

**Issue by IvanFarkas** [intel-iot-devkit/mraa#880]
Would it be possible to include **SWIG 4.0** to generate **.NET Core 2.1 C#** to use **MRAA** on **arm64v8**, please?
Has anything done in this area?
If not, how can I help, please?

**Comment by arfoll** [comment]
Well I know very little about .net but youd need to add a swig interface
file and that's no problem..

As for arm64v8 I don't have many arm targets but feel free to add some to
arm/ I don't believe you need to change anything for arm64v8 specifically?

**Comment by alext-mkrs** [comment]
@IvanFarkas, and what's your end goal, which specific .NET implementation (.NET Core, Mono)?

As for arm architecture specifically - as @arfoll said, it's a bit irrelevant and orthogonal to the language bindings. Architecture comes into play when we are talking about specific target boards you want to run mraa on. Which one you have in mind here?

**Comment by Propanu** [comment]
Due to the similarities between C# and Java, I think the best approach to this would be to look at how we currently generate our Java bindings and go from there. SWIG will play the biggest role here. Is .NET Core a subset of .NET for Windows IoT Core? Sorry, I haven't kept up with .NET for some time, but the idea of developing a C# app with MSVS and running it on a Linux target with Mono/.NET Core is very enticing.

**Comment by IvanFarkas** [comment]
Thank you very much @arfoll @alext-mkrs @Propanu for the quick feedback.
The target board is **arm64v8 DragonBoard 410c, DragonBoard 820c**.
I like the **Java to C# conversion**. That's what I would've done as well.

**Comment by alext-mkrs** [comment]
Let's continue in #778, so that we have only one thread going.

@propanu, .NET Core is Microsoft's alternative and open-source implementation of the .NET Standard - [here's](https://msdn.microsoft.com/en-us/magazine/mt842506.aspx) a nice general overview.

**Comment by IvanFarkas** [comment]
Sounds great

**Comment by arfoll** [comment]
little title change since at first I thought this was about SWIG 4.0 :D

**Comment by IvanFarkas** [comment]
Make sense. Thx.

**Comment by deinok** [comment]
https://www.nuget.org/packages/SystemExt.Devices.Mraa/

**Comment by IvanFarkas** [comment]
Awesome! I need it on Linux arm64 on DragonBoard 820c using .NET Core 2.2 C#.
Is it available for Linux arm64 (Debian)?
Perhaps GitHub source?

**Comment by deinok** [comment]
https://github.com/SystemExt/SystemExt.Devices.Mraa
It should work on any device that can run netstandard1.1 and have a `libmraa` installed.
In the near future you are not going to need libmraa installed in the SO, It will use a precompiled version attached to the nuget package

**Comment by deinok** [comment]
@IvanFarkas Now we have a way to include MRAA without with just adding a NuGet Package. It doesn't require having it installed.
