### ISSUE TITLE
O_CLOEXEC not found at make on UP running Ubilinux v3

### ISSUE THREAD

**Issue by Corusco** [intel-iot-devkit/mraa#882]
As indicated in the subject line, I'm getting a compile error of O_CLOEXEC undeclared when building. It first pops up at `gpio_chardev.c` line 170, func `mraa_get_chip_info_by_path`.

This is compiling on an Aaeon UP running Ubilinux v3. I can run the cmake portion just fine minus the SWIG and GTest, as I won't be using either. 

Given this def is part of POSIX 2008, I'm surprised to have this pop up. Any ideas?

**Comment by Propanu** [comment]
What compiler & version are you using?

**Comment by alext-mkrs** [comment]
@Corusco is this still actual? Please provide the requested information if yes.

**Comment by alext-mkrs** [comment]
Closing for no response.
