### ISSUE TITLE
UpSquared up2 not enough current passing through gpio

### ISSUE THREAD

**Issue by Nyceane** [intel-iot-devkit/mraa#884]
Hey guys, the gpio works, but when i connect it to a relay via D7 on grove shield, it would unlock the deadbolt on Arduino but wouldn't do it via up2 board, any ideas on how to fix it?

**Comment by alext-mkrs** [comment]
How do you think this could be related to mraa library, I wonder? :)

I'd suggest you to start with cross-checking the parameters or your relay vs parameters of the GPIOs provided by the Grove shield. If that's the grove relay you're talking about, I'd expect that to work and then please post the code you have + describe what exactly do you observe. That's still highly unlikely to be related to the library, but just for the fun of it, why not...

**Comment by alext-mkrs** [comment]
@Nyceane, is this still relevant?

**Comment by alext-mkrs** [comment]
Okay, but that again sounds like the HW part of your setup. Have you tried what I suggested in the previous comment? That simply sounds like your relay isn't compatible with your board's GPIO electrical params, that's it.

Anyway, as this sounds to be solved - I'm closing this one. Let us know if any further help is needed.
