### ISSUE TITLE
Up2 board, ValueError: Error initialising UART

### ISSUE THREAD

**Issue by Nyceane** [intel-iot-devkit/mraa#885]
Can not run the sample UART files...

Initializing UART...Traceback (most recent call last):
  File "uart_sender.py", line 34, in <module>
    u = mraa.Uart("0")
  File "/usr/lib/python3.5/dist-packages/mraa.py", line 1061, in __init__
    this = _mraa.new_Uart(*args)
ValueError: Error initialising UART

**Comment by malikabhi05** [comment]
so a couple of quick questions on this. What OS are you using ubilinux/ubuntu? and also did you get from the ppa or did you build it on your system? Also whats your mraa version?

**Comment by alext-mkrs** [comment]
+ please post the syslog/journal output around the time you run this - mraa may be logging additional useful information there.

**Comment by malikabhi05** [comment]
@Nyceane #878 This commit actually resolves an issue similar to what you're seeing. Because this fix is fairly recent, you might not have it if you installed mraa from ppa. However, if you build mraa locally, you should be able to get UART to work on the UP2 board.

**Comment by alext-mkrs** [comment]
@Nyceane, is this still actual?

**Comment by Nyceane** [comment]
yes, using Ubuntu

**Comment by alext-mkrs** [comment]
What about other questions? That information is necessary to understand the situation and help you.

**Comment by alext-mkrs** [comment]
So @Nyceane, are you up to providing the information requested? Without it we can't help you any further.

**Comment by alext-mkrs** [comment]
Closing for no reply.
