### ISSUE TITLE
mraa problem with Galileo Gen 2 and IOT Dev kit image

### ISSUE THREAD

**Issue by fduignan** [intel-iot-devkit/mraa#89]
There seems to be a problem using mraa with python on the Gen 2 Galileo board
Intel IoT Development Kit Version 1.1 
Kernel version: Linux quark017f89 3.8.7-yocto-standard #1 Wed Sep 3 10:41:56 BST 2014 i586 GNU/Linux 
mraa version: v0.5.4-64-g3efb7a0
Sample python code:

import mraa as m
spi_test = m.Spi(0)

Python returns error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mraa.py", line 757, in __init__
    this = _mraa.new_Spi(*args)
ValueError: Error initialising SPI bus

Error reported via journalctl is as follows:
Jan 08 20:39:44 quark017f89 libmraa[213]: gpio: Failed to write to export
Jan 08 20:39:44 quark017f89 libmraa[213]: spi: failed to set-up spi mosi multiplexer

**Comment by tingleby** [comment]
Confirmed. Investigating.
