### ISSUE TITLE
Help needed installing mraa for intel galileo

### ISSUE THREAD

**Issue by MagdyA** [intel-iot-devkit/mraa#890]
Can someone tell me what are the prerequisites and steps needed to install **latest** mraa and upm on intel galileo with yocto image on it?

I could install it once 2 months ago with an old read me file on the repo which had clearer steps for installing.

things got changed and I can't remember how I did it so I tried as docs says in here
![image](https://user-images.githubusercontent.com/22565650/38473378-88c5f3ea-3b8f-11e8-8893-80ea84c69a57.png)
but I get error in command **make** that I must use c99 flag and here is the full error message I get on the terminal

https://pastebin.com/guDYxNua

I'm a total newbie so pardon me for any stupid step I made.

**Comment by arfoll** [comment]
Your compiler is *old* so default C standard is also old. Add -DCMAKE_C_FLAGS="-std=gnu99" to your cmake line (make sure to wipe the build/ dir before hand).

I made a branch c99x with a probable fix and will probably merge something like that in next few days. Other option is just to compile latest stable afaik that still works.

**Comment by MagdyA** [comment]
Sounds like it. Thanks for your support

**Comment by alext-mkrs** [comment]
Closing as clarified.
