### ISSUE TITLE
PWM example for EDISON

### ISSUE THREAD

**Issue by elgarbe** [intel-iot-devkit/mraa#901]
Is [this](https://github.com/intel-iot-devkit/mraa/blob/master/examples/c/pwm.c#L38) line ok?
PWM are on MRAA 21, 0, 14 and 20 why it is using 3? I get an error using 3.

I don't get error using 21, but not PWM output on PWM3, GP183...

**Comment by arfoll** [comment]
Edison with which baseboard? With arduino board 3 is valid on default swizzler positions (I've never tried to support any other!)

**Comment by alext-mkrs** [comment]
So the example is intended to be used with the Arduino board, that's why it uses pin 3. I think we've clarified this, so closing. Feel free to comment if any further help is needed.
