### ISSUE TITLE
Problem: Analogic port not found in dragonboard

### ISSUE THREAD

**Issue by wallacejsb** [intel-iot-devkit/mraa#927]
Using mraa v1.9.0,  g++ 7.3
Board: Dragonboard 420C
OS: Linux linaro-developer 4.14.0-qcomlt-arm64 #1 SMP PREEMPT Fri May 25 18:39:49 UTC 2018 aarch64 GNU/Linux

Example code:
#include <mraa/common.hpp>
#include <mraa/aio.hpp>

#define AIO_PORT 0

int main(void){

    float float_value;
    mraa::Aio aio(AIO_PORT);
    while (true) {
	int value = aio.read();
        float_value = aio.readFloat();
        std::cout << "ADC A0 read %X - %d" << value << value << std::endl;
        std::cout << "ADC A0 read float - %.5f" << float_value << std::endl;
    }
    return EXIT_SUCCESS;
}

Commands:  
$ g++ program.cpp -o program -lmraa
$ sudo ./program

Output:  
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid AIO pin specified - do you have an ADC?
Aborted

Note: 
The command: 
$ ls /sys/bus
aio not found!

**Comment by Mani-Sadhasivam** [comment]
Hi @wallacejsb,

There is no onboard analog devices in Dragonboard410c, so `AIO` will not work. However, there is an Analog port which will let you connect analog devices using expansion boards such as [Audio Mezzanine](https://www.96boards.org/products/mezzanine/). Then you may need to do modifications on your own.
