### ISSUE TITLE
Info required: No of I2C devices that can be accessed simultaneously on Grove PI+ platform using mraa

### ISSUE THREAD

**Issue by BinduRao2018** [intel-iot-devkit/mraa#932]
I have connected  > 1 device/sensor  on Grove PI+ - I2C ports (Port I2C-2, I2C-1, I2C-3). I would like to read from/write to these devices simultaneously. I would like to know if there is any restriction w.r.t no of devices(slaves) that can be addressed by the bus

**Comment by Propanu** [comment]
Hi @BinduRao2018, you can definitely use multiple devices on the I2C bus. The biggest limiting factor is the total capacitance of the bus, as every device you add will make the signals a bit weaker. There are definitely exceptions though as some devices, especially ones that are not 100% compliant with the I2C protocol may not allow you to attach additional devices to the same bus.

**Comment by tingleby** [comment]
Also worth noting, if the i2c device(sensor) has the same address on more than one, that can cause a problem too.

**Comment by BinduRao2018** [comment]
Thanks for the information.

**Comment by alext-mkrs** [comment]
Looks like answered - closing
