### ISSUE TITLE
galileo gen1 initalisation is treated as 'error'

### ISSUE THREAD

**Issue by arfoll** [intel-iot-devkit/mraa#99]
There is no 'correct' gen1 initialisation anymore meaning we print an error message even if it isn't the case.

https://github.com/intel-iot-devkit/mraa/blob/master/src/x86/x86.c#L63

**Comment by alext-mkrs** [comment]
Just to make sure I understand the intent - we simply don't want to log this a namely error (but e.g. notice) or we want to change the init logic and e.g. stop using Gen1 clause as a fallback?

Feel free to assign this one to me, BTW - I'll drive it to closure.

**Comment by arfoll** [comment]
@alext-mkrs gen1 as fallback is ok I think, I dont have a better idea for now so I don't want to change the behaviour for now.

The issue is that there there should be an `else if (strncasecmp(line, "Galileo", x)` and then the default should do the same but also log an error. Does that make sense?

**Comment by alext-mkrs** [comment]
Yep, it does, thanks. Let me implement that.
